spring:
  application:
    name: authentication-service
  #  datasource:
  #    hikari:
  #      jdbc-url: jdbc:mysql://localhost:3307/bookstore
  #      username: root
  #      password: admin123
  #      maximum-pool-size: 10
  #      minimum-idle: 5
  #      idle-timeout: 30000
  #      connection-timeout: 30000
  #      max-lifetime: 60000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3307/bookstore
    username: root
    password: chuong0105
file:
  path: F:/upload